export class InvalidCredentialsException extends Error {}
export class UserNotFoundException extends Error {}
export class EmailAlreadyInUseException extends Error {}
export class WeakPasswordException extends Error {}
export class TokenExpiredException extends Error {}
export class NetworkException extends Error {}
export class TooManyRequestsException extends Error {}
export class PasswordResetFailedException extends Error {}
export class LogoutFailedException extends Error {}
export class AuthOperationFailedException extends Error {}
